name: ForDev
description: Enquetes para programadores.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito:
  faker:
    
flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/
